apiVersion: v1
kind: PersistentVolume
metadata:
  name: share2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.119.137
    path: "/share2"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.119.137
    path: "/share1"
